### ISSUE TITLE
Modularize  the Models

### ISSUE THREAD

**Issue by huytd** [huytd/codedaily-v3#22]
So, we have some models like Users, Auth, Sites, Links.

All of them are now living in `models.rs`, it's a good time to modularize them so each of them will have their own file.

**Comment by qcam** [comment]
@huytd Ok to close this now? #27 is merged.

**Comment by huytd** [comment]
@phsym @qcam Thank you so much for the great work! Now closed 👏

**Comment by huytd** [comment]
@phsym @qcam Thank you so much for the great work! Now closed :clap
