### ISSUE TITLE
www/build.js

### ISSUE THREAD

**Issue by qcam** [huytd/codedaily-v3#4]
I'm not sure if it is conventionally a good practice to keep build artifacts like `www/build.js` in the repo.

**Comment by huytd** [comment]
But I like it :(

**Comment by hngnaig** [comment]
@huytd 👎

**Comment by ldhnam** [comment]
@huytd 👎

**Comment by huytd** [comment]
@huytd 👍

**Comment by huytd** [comment]
Comrades, to avoid the upcoming rebellion, I close this issue and shutdown the communication.
